OpenLdap:
  Image: "docker.io/osixia/openldap"
  ImageTag: "latest"
  ImagePullPolicy: "Always"
  Component: "openldap"
  Replicas: 1
  Cpu: "512m"
  Memory: "200Mi"
  Organisation: "RHID."
  Domain: "myldap.demo"
  AdminPassword: "welcome1"
  SeedUsers: 
    usergroup: "ocpusers"
    userlist: "user1,user2,user3,user4"
    initialPassword: "welcome1"

PhpLdapAdmin:
  Component: "phpadmin"
  Image: "docker.io/osixia/phpldapadmin"
  ImageTag: "latest"
  ImagePullPolicy: "Always"
  Replicas: 1
  Cpu: "512m"
  Memory: "200Mi"
  Https: "false"
